### PR TITLE
Rename workflows, variables

### PR DESCRIPTION
**Pull request by effigies**
Anatomical only right now. But so you can see where I'm going with this and stop me if I'm misinterpreting.

### CODE REVIEW

**Comment by chrisgorgo** [comment]
Yup - this is what I had in mind. We should probably also add a line to CONTRIBUTIONS about it

**Comment by effigies** [comment]
Along with moving from `t1w` to `anat` in workflow names, thinking of moving from `bold` to `func`, to mirror BIDS directories. (Not changing filenames at this point.)

**Comment by effigies** [comment]
Wasn't sure how readable this would be all in one, so did it one or two workflows at a time. Hopefully each commit is pretty understandable.

**Comment by effigies** [comment]
I can add to contributions if I get a minute tonight or first thing in the morning.

**Comment by chrisgorgo** [comment]
I think there are still a couple of errors in documentation.

**Comment by effigies** [comment]
Thanks for the bump. I forgot to check the build status of this one.

**Comment by effigies** [comment]
Sorry about the delay. This should be good.

**Comment by chrisgorgo** [comment]
Thanks!

**Pull request merged**
